ALTER TABLE CONSULTAS ADD (DATE_QUERY_TMP DATE);

UPDATE CONSULTAS
SET DATE_QUERY_TMP =
    CASE
        WHEN REGEXP_LIKE(DATE_QUERY, '^\d{4}-\d{2}-\d{2}$') THEN TO_DATE(DATE_QUERY, 'YYYY-MM-DD')
        WHEN REGEXP_LIKE(DATE_QUERY, '^\d{2}-\d{2}-\d{4}$') THEN TO_DATE(DATE_QUERY, 'DD-MM-YYYY')
        ELSE SYSDATE
    END;

ALTER TABLE CONSULTAS DROP COLUMN DATE_QUERY;

ALTER TABLE CONSULTAS RENAME COLUMN DATE_QUERY_TMP TO DATE_QUERY;

ALTER TABLE CONSULTAS MODIFY (INDICATOR VARCHAR2(20));
ALTER TABLE CONSULTAS MODIFY (SOURCE VARCHAR2(50));

ALTER TABLE USERS RENAME COLUMN NAME TO USERNAME;

COMMIT;
